apiVersion: v1
kind: Service
metadata:
  name: reference-service
  namespace: reference-service-showcase
spec:
  selector:
    app.kubernetes.io/name: reference-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reference-service
  namespace: reference-service-showcase
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: reference-service
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reference-db-service
  namespace: reference-service-showcase
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: reference-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: reference-podinfo-service
  namespace: reference-service-showcase
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: pod-info
  ports:
    - protocol: TCP
      port: 9898
      targetPort: 9898