apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-pipeline-run
  namespace: reference-service-ci
spec:
  pipelineRef:
    name: ci-pipeline
  workspaces:
    - name: git-credentials
      secret:
        secretName: git-credentials
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  params:
    - name: repo-url
      value: git@github.com:GITHUB_REPOSITORY.git
    - name: refspec
      value: GITHUB_REF
    - name: repo-name
      value: GITHUB_REPOSITORY