FROM golang:1.19.2-alpine3.16 AS builder
WORKDIR /app
COPY . /app

RUN go build -o reference-app-go /app/cmd/service/main.go

FROM alpine:3.13

COPY --from=builder /app/reference-app-go ./

RUN apk add curl

CMD ["./reference-app-go"]