{{- $registry := .Values.registry | required ".Values.registry is required." -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-service
  labels:
    app.kubernetes.io/name: reference-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reference-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reference-service
    spec:
      containers:
        - name: reference-service
          image: {{ $registry }}/{{ .Values.service.image }}
          {{- if .Values.service.environmentVariables }}
          env:
            {{- range $key, $value := .Values.service.environmentVariables }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
          {{- end }}
          ports:
            - containerPort: 8080
