baseURL = 'https://learn.cecg.io/'
languageCode = 'en-us'
title = 'CECG Bootcamp'
theme = 'hugo-theme-learn'
enableEmoji = true
[params]
  themeVariant = "cecg"
  editURL = "https://github.com/coreeng/website-bootcamp/edit/main/static-site/content/"
[outputs]
home = [ "HTML", "RSS", "JSON"]
