baseURL = 'https://learn.cecg.io/'
languageCode = 'en-us'
title = 'CECG Bootcamp'
theme = 'hugo-theme-learn'
enableEmoji = true
[params]
  themeVariant = "cecg"
  editURL = "https://github.com/coreeng/knowledge-platform/tree/main/knowledge-base/content"
[outputs]
home = [ "HTML", "RSS", "JSON"]
