{{- $module := .Values.module | required ".Values.module is required." -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $module }}-acceptance-tests
  namespace: {{ $module }}-autograding
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ $module }}-acceptance-tests
          image: cecg/{{ $module }}-autograding
          imagePullPolicy: Never
