{{- $registry := .Values.registry | required ".Values.registry is required." -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-db
  labels:
    app.kubernetes.io/name: reference-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reference-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reference-db
    spec:
      containers:
        - name: reference-db
          image: postgres:15.0-bullseye
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
                  optional: false
---
apiVersion: apps/v1 # Remove this from here - can be assumed its a dependency stub
kind: Deployment
metadata:
  name: pod-info
  labels:
    app.kubernetes.io/name: pod-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pod-info
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pod-info
    spec:
      containers:
        - name: pod-info
          image: stefanprodan/podinfo:6.2.2
          ports:
            - containerPort: 9898
