apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: ramp-up
spec:
  parallelism: 1
  arguments: -o output-prometheus-remote --tag test_name=ramp-up
  runner:
    image: cecg/k6-prom:latest
    env:
      - name: SERVICE_ENDPOINT
        value: "http://reference-service.reference-service-showcase.svc.cluster.local."
      - name: K6_PROMETHEUS_REMOTE_URL
        value: http://prom-kube-prometheus-stack-prometheus.default.svc.cluster.local:9090/api/v1/write
  script:
    configMap:
      name: ramp-up
      file: test.js