name: Bootcamp-content-CI

on:
  push:
    branches:
      - master
      - initialization_tool
    paths:
      - "cecg-bootcamp-content/**"
  pull_request:
    branches:
      - master
    paths:
      - "cecg-bootcamp-content/**"

jobs:
  docker:
    runs-on: ubuntu-latest
#    if: github.event_name == 'push' && github.ref == 'refs/heads/master' || github.ref == '/refs/heads/initialization_tool'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: cecg-bootcamp-content/.
          platforms: linux/amd64,linux/arm64
          push: true
          tags: cecg/cecg-bootcamp:latest