name: Reference-app-go-CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      -
jobs:
  Stubbed-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        working-directory: reference-application-go
        run: |
          pwd=$(pwd)
          ls=$(ls)
          echo 'PWD'
          echo $pwd
          echo 'LS'
          echo $ls
          make build
      - name: Stubbed-Functional
        working-directory: reference-application-go
        env:
          SERVICE_ENDPOINT: 'http://service:8080'
        run: |
          make local-stubbed-functional
      - name: Stubbed-NFT
        working-directory: reference-application-go
        run: |
          make local-stubbed-nft
