name: Reference-app-java-CI

on:
  push:
    branches:
      - master
    paths:
      - "reference-application-go/**"
  pull_request:
    branches:
      - master
    paths:
      - "reference-application-go/**"

jobs:
  Stubbed-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        working-directory: reference-application-java
        run: |
          make build
      - name: Stubbed-Functional
        working-directory: reference-application-java
        env:
          SERVICE_ENDPOINT: 'http://service:8080'
        run: |
          make local-stubbed-functional
      - name: Stubbed-NFT
        working-directory: reference-application-java
        run: |
          make local-stubbed-nft