name: Reference-app-java-CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Stubbed-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: |
          make build
      - name: Setup minikube
        id: minikube
        uses: medyagh/setup-minikube@master
        with:
          driver: docker
          cni: bridge
          addons: registry,ingress # addons for minikube
          insecure-registry: 'localhost:5000,10.0.0.0/24'
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - name: Configure Docker-Minikube registry
        run: |
          docker run -d --rm --network=host alpine ash -c "apk add socat && socat TCP-LISTEN:5000,reuseaddr,fork TCP:$(minikube ip):5000"
      - name: Docker build and push
        working-directory: reference-application-java
        run: |
          make docker-build-push-all
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Deploy Reference App
        working-directory: reference-application-java
        run: |
          make helm-deploy
      - name: Test Reference App
        working-directory: reference-application-java
        run: |
          make helm-test
